import React from 'react';
import { useNavigate } from 'react-router-dom';
import Icon from '../../../components/AppIcon';
import Image from '../../../components/AppImage';

export default function VideoRecommendations({ nextVideo, seriesVideos = [], className = '' }) {
  const navigate = useNavigate();
  const openVideo = (video) => navigate(`/training-video-player/${video.id}`, { state: { video } });
  return <aside dir="rtl" className={`space-y-5 ${className}`}>
    {nextVideo && <section className="academy-surface p-4"><div className="mb-3 flex items-center gap-2"><Icon name="PlayCircle" size={18} className="text-[#df6b52]" /><h3 className="font-black text-[#1c2c29]">جلسه بعدی</h3></div><button type="button" onClick={() => openVideo(nextVideo)} className="group w-full overflow-hidden rounded-2xl bg-[#1c2c29] text-right text-white"><div className="relative aspect-[16/8]"><Image src={nextVideo.thumbnail} alt={nextVideo.title || 'جلسه بعدی'} className="h-full w-full object-cover opacity-75 transition group-hover:scale-[1.02]" /><span className="absolute inset-0 flex items-center justify-center"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white text-[#1c2c29] shadow-lg"><Icon name="Play" size={19} className="fill-current" /></span></span></div><div className="p-4"><p className="font-black leading-7">{nextVideo.title}</p>{nextVideo.description && <p className="mt-1 line-clamp-2 text-xs leading-6 text-white/60">{nextVideo.description}</p>}</div></button></section>}
    {seriesVideos.length > 0 && <section className="academy-surface p-4 sm:p-5"><div className="mb-4 flex items-end justify-between"><div><p className="academy-kicker">مسیر یادگیری</p><h3 className="mt-1 font-black text-[#1c2c29]">فهرست جلسات</h3></div><span className="text-xs font-bold text-[#87928e]">{seriesVideos.length} جلسه</span></div><div className="space-y-2">{seriesVideos.map((video, index) => <button type="button" key={video.id} onClick={() => openVideo(video)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-right transition ${video.current ? 'border-[#df6b52] bg-[#fff4ef]' : 'border-transparent bg-[#f7f4ed] hover:border-[#cfd4cf]'}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-xs font-black ${video.completed ? 'bg-[#dce8db] text-[#34613e]' : video.current ? 'bg-[#df6b52] text-white' : 'bg-white text-[#66736e]'}`}>{video.completed ? <Icon name="Check" size={16} /> : video.current ? <Icon name="Play" size={14} /> : index + 1}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[#1c2c29]">{video.title || video.description || `جلسه ${index + 1}`}</strong><small className="mt-1 block text-[#87928e]">{video.duration ? `${video.duration} دقیقه` : 'ویدیوی آموزشی'}</small></span>{video.current && <span className="text-[10px] font-black text-[#b84f3a]">در حال پخش</span>}</button>)}</div></section>}
    <button type="button" onClick={() => navigate('/user-dashboard')} className="academy-secondary-button w-full"><Icon name="ArrowRight" size={17} />بازگشت به خانه</button>
  </aside>;
}
